export const EMOJI_MAP = {
  "cuore": "❤️",
  "proibito": "🚫",
  "vietato": "🚫",
  "amore": "❤️",
  "amare": "❤️",
  "giudizio":"⚖️",
  "giustizia":"⚖️",
  "giustizie":"⚖️"
};

export const TEXT = {
  lang: "it",
  subtitle: "Indovina la parola aggiungendo le vocali.",
  startTitle: "Configura partita",
  players: "Numero di giocatori",
  playerColorsTitle: "Colori dei giocatori",
  choosePlayerColor: "Scegli il colore per il Giocatore {n}",
  time: "Tempo massimo per turno (secondi)",
  rounds: "Round di indizi prima di rivelare",
  categoriesTitle: "Categorie",
  randomCategories: "Scegli a caso",
  categoryCount: "Seleziona le categorie che entreranno in gioco.",
  startGame: "Inizia partita",
  selectCategories: "Devi selezionare esattamente {n} categorie.",
  round: "Round",
  turn: "Turno di",
  seconds: "sec",
  boardTitle: "Parole scoperte",
  guessedWordTitle: "Parola Corretta!",
  guessPlaceholder: "Scrivi la parola",
  guessPartPlaceholder: "Scrivi la parola {n}",
  categoryPlaceholder: "Scegli una categoria",
  guess: "RISPONDI",
  pause: "Pausa",
  resume: "Riprendi tempo",
  correct: "Corretto! Parola e categoria.",
  wordOnly: "Hai indovinato la parola, ma non la categoria.",
  categoryOnly: "Hai indovinato la categoria, ma non la parola.",
  wordOnlyPoints: "Hai indovinato la parola. +{points} punti.",
  categoryOnlyPoints: "Hai indovinato la categoria. +{points} punti.",
  compoundOneOnly: "Hai indovinato una delle due parole. +metà del punteggio.",
  compoundWordsButCategory: "Hai indovinato entrambe le parole, ma non la categoria. +{points} punti.",
  partialPoints: "Risposta parzialmente corretta. +{points} punti.",
  incorrect: "Non è corretto. Passa al giocatore successivo.",
  incorrectWordCorrectCategory: "Parola errata, categoria corretta.",
  timeout: "Tempo scaduto. Passa al giocatore successivo.",
  hintHelp: "({help})",
  hintSubcategory: "Sottocategoria: {category}",
  hintVowel: "",
  revealed: "La parola era:",
  computer: "COMPUTER",
  continue: "Continua",
  end: "Fine della partida",
  newGame: "Nuova partita",
  points: "punti",
  noPoints: "senza punti",
  player: "Giocatore",
  category: "Categoria",
  fortext: "Commento",
  won: "Vincitore",
  tie: "Pareggio",
  categoryAlready: "Questa categoria è già stata selezionata.",
  noWords: "Non ci sono abbastanza parole valide nelle categorie selezionate.",
  specialRound: "Il computer rivela una parola.",
  remaining: "mancano",
  revealedWord: "Parola rivelata",
  revealedWordContinue: "La parola è stata rivelata. Premi CONTINUA per proseguire.",
  revealedUnansweredTitle: "Parola non indovinata",
  revealCategoryLabel: "Categoria",
  revealFortextLabel: "",
  revealWordLabel: "Parola",
  revealHelpLabel: "Aiuto",
  wordBlockCorrect: "Hai indovinato la parola.",
  wordPartialCorrect: "Hai indovinato parte della parola.",
  categoryCorrect: "Hai indovinato la categoria.",
  sortCategoriesLabel: "Ordina categorie",
  sortAZ: "A-Z",
  sortDifficulty: "Difficoltà",
  sortRandom: "Casuale",
  difficultyTagPrefix: "Difficoltà",
  tagsAll:"tutti",
    glosNameTitle:"Glossario dei Nomi",
  glosTitle:"Glossario di Parole",
  rulesTitle: "Regole del Gioco",
  rulesBody: `<p>1. Prova a indovinare le parole in MAIUSCOLO inserendo le vocali mancanti (+3 punti per parola)</p> <p>2. Bonus: Indovina la sottocategoria a cui appartiene (+1 punto)</p> <p>3. Se non indovini, il turno passerà al giocatore successivo.</p> <p>4. Se nessun giocatore indovina, la manche termina e vengono rivelati indizi e/o vocali per riprovare</p> <p>5. Puoi usare il pulsante "RIVELA INDIZIO" per forzare un indizio immediato in cambio di 1 punto.</p>`,
  closeRules: "Chiudi"
};

export function t(key, vars = {}) {
  let s = TEXT[key] ?? key;
  return s.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}
