export const EMOJI_MAP = {
  "heart": "❤️",
  "prohibited": "🚫",
  "forbidden": "🚫",
  "do not": "🚫",
  "love": "❤️",
  "mercy":"❤️",
  "justice":"⚖️",
  "judgment":"⚖️"
};

export const TEXT = {
  lang: "en",
  subtitle: "Guess the word by adding vowels.",
  startTitle: "Game Setup",
  players: "Number of players",
  playerColorsTitle: "Player colors",
  choosePlayerColor: "Choose color for Player {n}",
  time: "Maximum turn time (seconds)",
  rounds: "Clue rounds before reveal",
  glosNameTitle:"Names Glosarie",
  glosTitle:"Words Glosarie",
  categoriesTitle: "Categories",
  randomCategories: "Pick randomly",
  categoryCount: "Select the categories that will enter the game.",
  startGame: "Start Game",
  selectCategories: "You must select exactly {n} categories.",
  round: "Round",
  turn: "Turn of",
  seconds: "sec",
  boardTitle: "Discovered words",
  guessedWordTitle: "Word Guessed!",
  guessPlaceholder: "Type the word",
  guessPartPlaceholder: "Type word {n}",
  categoryPlaceholder: "Choose a category",
  guess: "GUESS",
  pause: "Pause",
  resume: "Resume time",
  correct: "Correct! Word and category.",
  wordOnly: "You guessed the word, but not the category.",
  categoryOnly: "You guessed the category, but not the word.",
  wordOnlyPoints: "You guessed the word. +{points} points.",
  compoundOneOnly: "You guessed one of two words. +half points.",
  compoundWordsButCategory: "You guessed both words, but not category. +{points} points.",
  partialPoints: "Partial success. +{points} points.",
  incorrect: "Incorrect. Next player's turn.",
  incorrectWordCorrectCategory: "Incorrect word, correct category.",
  timeout: "Time is up! Next player's turn.",
  hintHelp: "({help})",
  hintSubcategory: "Subcategory: {category}",
  hintVowel: "",
  revealed: "The word was:",
  computer: "COMPUTER",
  continue: "Continue",
  end: "End of game",
  newGame: "New Game",
  points: "points",
  noPoints: "no points",
  player: "Player",
  category: "Category",
  fortext: "Comment",
  won: "Winner",
  tie: "Tie",
  categoryAlready: "This category is already selected.",
  noWords: "Not enough valid words in selected categories.",
  specialRound: "The computer reveals a word.",
  remaining: "remaining",
  revealedWord: "Revealed word",
  revealedWordContinue: "Word revealed. Press CONTINUE to proceed.",
  revealedUnansweredTitle: "Unanswered word",
  revealCategoryLabel: "Category",
  revealFortextLabel: "",
  revealWordLabel: "Word",
  revealHelpLabel: "Help",
  wordBlockCorrect: "You guessed the word.",
  wordPartialCorrect: "You guessed part of the word.",
  categoryCorrect: "You guessed the category.",
  sortCategoriesLabel: "Sort categories",
  sortAZ: "A-Z ",
  sortDifficulty: "Difficulty",
  sortRandom: "Random",
  difficultyTagPrefix: "Difficulty",
  rulesTitle: "Game Rules",
  rulesBody: "<p>1. Try to guess the target word or words and the category they belong to.</p><p>2. If you guess only the category or part of a compound word, you will get partial points and the turn moves to the next player.</p><p>3. Connectors and lowercase words are visible; you only need to guess words in UPPERCASE.</p><p>4. As rounds progress, clues and vowels will be revealed.</p><p>5. You can use the 'REVEAL CLUE' button to force an immediate clue for 1 point.</p>",
  closeRules: "Close",
  tagsAll:"All"
};

export function t(key, vars = {}) {
  let s = TEXT[key] ?? key;
  return s.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}