export const EMOJI_MAP = {
  "corazon": "❤️",
  "corazón": "❤️",
  "prohibido": "🚫",
  "amor": "❤️",
  "amar": "❤️‍🔥💔",
  "juicio":"⚖️",
  "justicia":"⚖️",
  "justicias":"⚖️",
  "pide":"🙏"
};

export const TEXT = {
  lang: "es",
  subtitle: "Adivina la palabra agregando vocales.",
  startTitle: "Configurar partida",
  players: "Cantidad de jugadores",
  playerColorsTitle: "Colores de los jugadores",
  choosePlayerColor: "Elige el color para el Jugador {n}",
  time: "Tiempo máximo por turno (segundos)",
  rounds: "Rondas de pistas antes de revelar",
  glosNameTitle:"Glosario de Nombres",
  glosTitle:"Glosario de Palabras",
  categoriesTitle: "Categorías",
  randomCategories: "Elegir al azar",
  categoryCount: "Selecciona las categorías que entrarán en juego.",
  startGame: "Comenzar partida",
  selectCategories: "Debes seleccionar exactamente {n} categorías.",
  round: "Ronda",
  turn: "Turno de",
  seconds: "seg",
  boardTitle: "Palabras descubiertas",
  guessedWordTitle: "¡Palabra Adivinada!",
  guessPlaceholder: "Escribe la palabra",
  guessPartPlaceholder: "Escribe la palabra {n}",
  categoryPlaceholder: "Elige una categoría",
  guess: "RESPONDER",
  pause: "Pausa",
  resume: "Continuar tiempo",
  correct: "¡Correcto! Palabra y categoría.",
  wordOnly: "Has acertado la palabra, pero no la categoría.",
  categoryOnly: "Has acertado la categoría, pero no la palabra.",
  wordOnlyPoints: "Has acertado la palabra. +{points} puntos.",
  categoryOnlyPoints: "Has acertado la categoría. +{points} puntos.",
  compoundOneOnly: "Has acertado una de las dos palabras. +la mitad del puntaje.",
  compoundWordsButCategory: "Has acertado las dos palabras, pero no la categoría. +{points} puntos.",
  partialPoints: "Acierto parcial. +{points} puntos.",
  incorrect: "No es correcto. Le toca al siguiente jugador.",
  incorrectWordCorrectCategory: "Palabra incorrecta, categoría correcta.",
  timeout: "Se acabó el tiempo. Le toca al siguiente jugador.",
  hintHelp: "({help})",
  hintSubcategory: "Subcategoría: {category}",
  hintVowel: "",
  revealed: "La palabra era:",
  computer: "ORDENADOR",
  continue: "Continuar",
  end: "Fin de la partida",
  newGame: "Nueva partida",
  points: "puntos",
  noPoints: "sin puntos",
  player: "Jugador",
  category: "Categoría",
  fortext: "Comentario",
  won: "Ganador",
  tie: "Empate",
  categoryAlready: "Esta categoría ya está seleccionada.",
  noWords: "No hay suficientes palabras válidas en las categorías seleccionadas.",
  specialRound: "El ordenador revela una palabra.",
  remaining: "faltan",
  revealedWord: "Palabra revelada",
  revealedWordContinue: "Se reveló la palabra. Pulsa CONTINUAR para seguir.",
  revealedUnansweredTitle: "Palabra no adivinada",
  revealCategoryLabel: "Categoría",
  revealFortextLabel: "",
  revealWordLabel: "Palabra",
  revealHelpLabel: "Ayuda",
  wordBlockCorrect: "Has acertado la palabra.",
  wordPartialCorrect: "Has acertado parte de la palabra.",
  categoryCorrect: "Has acertado la categoría.",
  sortCategoriesLabel: "Ordenar categorías",
  sortAZ: "A-Z",
  sortDifficulty: "Dificultad",
  sortRandom: "Azar",
  difficultyTagPrefix: "Dificultad",
  tagsAll:"todos",
  rulesTitle: "Reglas del Juego",
  rulesBody: `<p>1. Intenta adivinar las palabras en MAYÚSCULA agregando las vocales que le faltan (+3 puntos por palabra)</p>
  <p>2. Bonus: Adivinar la sub-categoría a la que pertenece (+1 punto)</p>
  <p>3. Si no aciertas, el turno pasará al siguiente jugador.</p>
  <p>4. Si ningún jugador acierta, se termina la ronda y se revelan pistas y/o vocales para volver a intentar</p>
  <p>5. Puedes usar el botón "REVELAR PISTA" para forzar una pista inmediata a cambio de 1 punto.</p>`,
  closeRules: "Cerrar"
};

export function t(key, vars = {}) {
  let s = TEXT[key] ?? key;
  return s.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}
